"""The conformance documents in docs/conformance/, rendered from a run of the corpus.

Deterministic on purpose — sorted, with no timestamps or durations — so a committed document that
no longer matches a fresh run means something changed, and the gate can say so.
"""

from dataclasses import dataclass, field
from pathlib import Path

import duckdb
import tpch_data
from harness import compare, load_case, run_case

OUTCOMES = ("pass", "known_divergence", "fail")
CASES = Path(__file__).parent / "cases"
DOCUMENTS = Path(__file__).parents[2] / "docs" / "conformance"
DOCUMENTS_SCALE = 0.1  # the TPC-H scale factor the committed documents are generated at


@dataclass(frozen=True)
class EngineRun:
    name: str
    version: str


@dataclass(frozen=True)
class Result:
    catalog: str
    case: str
    engine: str
    outcome: str  # one of OUTCOMES
    divergence: str | None = None
    differences: list[str] = field(default_factory=list)


def _parity(results: list[Result], engines: list[EngineRun], tpch_scale: float) -> str:
    lines = [
        "# Conformance parity matrix",
        "",
        "Generated by `make conformance-docs` from the conformance corpus. Do not edit by hand.",
        "",
        "| Engine | Version | Cases | Pass | Known divergence | Fail | Status |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for engine in engines:
        ran = [r for r in results if r.engine == engine.name]
        counts = [sum(r.outcome == outcome for r in ran) for outcome in OUTCOMES]
        # Supported while every case passes or is a divergence recorded in failure-modes.
        status = "experimental" if any(r.outcome == "fail" for r in ran) else "supported"
        lines.append(
            f"| {engine.name} | {engine.version} | {len(ran)} | "
            + " | ".join(map(str, counts))
            + f" | {status} |"
        )
    lines += [
        "",
        f"TPC-H scale factor: {tpch_scale:g}",
        "",
        "| Catalog | Case | " + " | ".join(engine.name for engine in engines) + " |",
        "| --- | --- | " + " | ".join("---" for _ in engines) + " |",
    ]
    outcome = {(r.catalog, r.case, r.engine): r.outcome for r in results}
    for catalog, case in sorted({(r.catalog, r.case) for r in results}):
        cells = [outcome[catalog, case, engine.name].replace("_", " ") for engine in engines]
        lines.append(f"| {catalog} | {case} | " + " | ".join(cells) + " |")
    return "\n".join(lines) + "\n"


def _divergences(results: list[Result]) -> str:
    text = (
        "# Conformance divergences\n"
        "\n"
        "Generated by `make conformance-docs` from the conformance corpus. Do not edit by hand.\n"
        "Each heading is an entry in [`docs/failure-modes.md`](../failure-modes.md); the cases\n"
        "under it still differ from their reference, which stays as the reference computed it.\n"
    )
    marked = [r for r in results if r.outcome == "known_divergence"]
    for divergence in sorted({r.divergence for r in marked}):
        text += f"\n## {divergence}\n\n"
        for r in sorted(
            (r for r in marked if r.divergence == divergence),
            key=lambda r: (r.engine, r.catalog, r.case),
        ):
            text += f"- {r.engine} · {r.catalog}/{r.case}\n"
            text += "".join(f"  - {difference}\n" for difference in r.differences)
    return text


def render(results: list[Result], engines: list[EngineRun], tpch_scale: float) -> dict[str, str]:
    """The text of each document, by file name."""
    return {
        "parity.md": _parity(results, engines, tpch_scale),
        "divergences.md": _divergences(results),
    }


def collect() -> tuple[list[Result], list[EngineRun], float]:
    """Run every case on every available engine: DuckDB only, until the other adapters exist."""
    results = []
    for path in sorted(p for p in CASES.rglob("*") if p.suffix in (".yml", ".yaml")):
        case = load_case(path)
        answer, reference = run_case(case)
        differences = compare(answer, case, reference)
        if case.known_divergence and differences:
            outcome = "known_divergence"
        elif differences or case.known_divergence:
            outcome = "fail"  # a mark on a case that now agrees is stale, as the runner says
        else:
            outcome = "pass"
        results.append(
            Result(case.catalog, case.id, "DuckDB", outcome, case.known_divergence, differences)
        )
    return results, [EngineRun("DuckDB", duckdb.__version__)], tpch_data.SCALE


def main() -> None:
    if tpch_data.SCALE != DOCUMENTS_SCALE:
        raise SystemExit(
            f"the documents are generated at TPC-H scale factor {DOCUMENTS_SCALE:g}; "
            "unset METRICBRIDGE_TPCH_SCALE"
        )
    DOCUMENTS.mkdir(parents=True, exist_ok=True)
    for name, text in render(*collect()).items():
        (DOCUMENTS / name).write_text(text)
        print(f"wrote docs/conformance/{name}")


if __name__ == "__main__":
    main()
