"""TPC-H for the conformance corpus: generated by DuckDB's tpch extension on first use, cached
under `.cache/conformance/`, never committed.

`METRICBRIDGE_TPCH_SCALE` picks the scale factor: 0.1 by default (pull requests), 1 nightly.
"""

import os
from functools import cache
from pathlib import Path

import duckdb

CACHE = Path(__file__).parents[2] / ".cache" / "conformance"


@cache
def tpch_database() -> Path:
    scale = float(os.environ.get("METRICBRIDGE_TPCH_SCALE", "0.1"))  # a number before it is SQL
    # Not tpch.duckdb: DuckDB names the catalog after the file, which would make every
    # `tpch.<table>` reference ambiguous with the schema.
    path = CACHE / f"tpch-sf{scale:g}.duckdb"
    if path.exists():
        return path
    CACHE.mkdir(parents=True, exist_ok=True)
    partial = path.with_suffix(".partial")  # renamed only when complete
    partial.unlink(missing_ok=True)
    with duckdb.connect(str(partial)) as connection:
        connection.execute("SET enable_progress_bar = false")
        connection.execute("INSTALL tpch")
        connection.execute("LOAD tpch")
        connection.execute("CREATE SCHEMA tpch")
        connection.execute(f"CALL dbgen(sf = {scale}, schema = 'tpch')")
    partial.rename(path)
    return path
